name: Minecraft Server

on:
  workflow_dispatch:

jobs:
  minecraft:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Create Server Folder
        run: mkdir server

      - name: Download PaperMC
        run: |
          cd server
          wget https://api.papermc.io/v2/projects/paper/versions/1.21.5/builds/24/downloads/paper-1.21.5-24.jar -O paper.jar

      - name: Accept EULA
        run: |
          cd server
          echo "eula=true" > eula.txt

      - name: Start Server
        run: |
          cd server
          java -Xms2G -Xmx2G -jar paper.jar nogui
